name: go_stop_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.0
  google_fonts: ^5.0.0
  shared_preferences: ^2.2.2
  # Supabase 관련 패키지들
  supabase_flutter: ^2.3.4
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  # 소셜 로그인 패키지들
  flutter_facebook_auth: ^6.1.1
  flutter_dotenv: ^5.1.0
  shimmer: ^3.0.0
  # URL 처리
  url_launcher: ^6.2.5
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/avatars/
    - assets/backgrounds/
    - assets/cards/
    - assets/icons/coin.png
    - assets/sounds/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
          weight: 100
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
          weight: 200
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
          weight: 300
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
          weight: 400
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
          weight: 500
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
          weight: 600
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
          weight: 700
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf
          weight: 800
